### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by geekmc** [zhangxiaoyang/WechatImageDecoder#3]
为什么每次还原后都打不开呢？提示文件损坏

**Comment by zhangxiaoyang** [comment]
如果不涉及隐私，请私心我图片。我刚才试了下，是可以还原PC端的图片的。

**Comment by geekmc** [comment]
我加 你个联系方式吧，我的WX：ma1993714

**Comment by zhangxiaoyang** [comment]
不建议在此留个人信息。

你可以把文件（最好是非隐私图片，多个）发我邮箱 zhangxiaoyang.hit#gmail.com，我尝试decode一下。

也请附上微信PC端版本号、手机型号、微信手机版本号，谢谢。

**Comment by icaca** [comment]
bmp 和 png 解不了

**Comment by zhangxiaoyang** [comment]
@icaca supported

https://github.com/zhangxiaoyang/WechatImageDecoder/commit/09282747bd2b9fcc6d15e88ca456405f20343217

**Comment by icaca** [comment]
文件是dat的，如何知道应该选择哪种文件进行转换呢

**Comment by zhangxiaoyang** [comment]
@icaca 
https://github.com/zhangxiaoyang/WechatImageDecoder/commit/d12137bfc99c62dafdee017d51f823fb4a23c5c0
